server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git: #default
          uri: file:///Users/jeongdonghun/Desktop/git-local-repo
          default-label: master
